### ISSUE TITLE
docker-compose fail

### ISSUE THREAD

**Issue by unfirth** [mike61988/magento2-dk#10]
When I try to run docker-compose -f docker-compose_windows.yml up -d

here's what I get: 

Creating network "magento2-dk_default" with the default driver
Building base
Step 1/30 : FROM debian:latest
latest: Pulling from library/debian
ERROR: Service 'base' failed to build: no matching manifest for windows/amd64 10.0.18363 in the manifest list entries

**Comment by unfirth** [comment]
(Update) I set Docker to experimental and I got a bit further along. Here's the output: 
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [187 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7380 B]
Fetched 8338 kB in 3s (2469 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
1 package can be upgraded. Run 'apt list --upgradable' to see it.
ERROR: Service 'base' failed to build: The command '/bin/sh -c apt update' returned a non-zero code: 4294967295: failed to shutdown container: container cd2c11d3289e4ad973a5393fbd63acb6fe656107f07628d90c367b34031ecb46 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container cd2c11d3289e4ad973a5393fbd63acb6fe656107f07628d90c367b34031ecb46 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)

**Comment by mike61988** [comment]
Usually, I saw something similar to it on Windows with the wrong container mode, let's try to switch to Linux/Windows containers, depends on which exactly you are now, and do restart the Docker.

**Comment by mike61988** [comment]
I also would recommend a fresh install of the images, you may delete all of them, see link below:
https://github.com/mike61988/magento2-dk#how-to-uninstall-the-vm

and then start from the first step.

**Comment by unfirth** [comment]
ok - I did as you suggested and it seemed to work, but then I went to the next step and it said there was no such container.


Tim@Surface-Book MINGW64 ~
$ winpty docker exec -it m23 //bin/sh
Error: No such container: m23

Tim@Surface-Book MINGW64 ~
$ docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by mike61988** [comment]
Let me check with you: you deleted all the images and switched to another mode (which one btw?) and then did the very first step, this one docker-compose -f docker-compose_windows.yml up -d correct?

**Comment by unfirth** [comment]
Yes, but just in case I'm going to do today again. It is using Linux
container now.

**Comment by mike61988** [comment]
I've checked it on my other laptop (on Windows) I ran it on Linux container as well and it's working fine.

Let me know if you need any further help in the future.

Cheers
