### ISSUE TITLE
Error message during docker-compose command

### ISSUE THREAD

**Issue by joannehoaz** [mike61988/magento2-dk#16]
When running the command in the instructions:

composer create-project --repository=https://repo.magento.com/ magento/project-community-edition /var/www/html/magento2ce/ 

I'm getting an error message:

[InvalidArgumentException]                                                       
  Could not find package magento/project-community-edition with stability stable.  

Auth keys are correctly set up. Also tried updating the global config of .composer/auth.json and that fails.

Trying to specify a specific version of the community edition (tried 2.3.5-p1, 2.3.4, 2.3.3, 2.3.2) also fails with the same error message.

Installing community edition manually works but then if I comment out the create-project command in the docker file, the subsequent command fails.

Anything else I can try? Thanks for the help!

**Comment by mike61988** [comment]
Looks like it's something temporary issue.
May you please confirm if you still experiencing this one?

**Comment by mike61988** [comment]
closed due to inactivity
