### ISSUE TITLE
Can't build docker images, authentication error

### ISSUE THREAD

**Issue by pagito** [mike61988/magento2-dk#6]
Using windows, besides that all keys are provided generated on marketplace still getting the error: You haven't provided your Magento authentication keys. Anything I'm not doing correctly?

Thanks!

**Comment by mike61988** [comment]
Hi, 

I have an assumption that you haven't provided authentication keys the first time and now you have incorrect keys inside the container. Try to remove all images and do the setup again.

Thanks,
