### ISSUE TITLE
authentication problem - need advice

### ISSUE THREAD

**Issue by adammberk** [mike61988/magento2-dk#8]
Following the instructions for windows install
configured auth.json as documented in path C:\sites\magento2-dk\debian_config\composer\auth.json

{
    "http-basic": {
        "repo.magento.com": {
            "username": "ef85603xxxxxxxx370f80f4",
            "password": "943417xxxxxxx3bbfee276"
        }
    }
}

while running docker-compose -f ..\docker-compose_windows.yml up -d
received the following error and termination.  The keys I used were what I have in my magento account as enabled.  
What might be the problem?

Creating a "magento/project-community-edition" project at "/var/www/html/magento2ce"
Warning from repo.magento.com: Your Magento authentication keys are invalid. Please double-check your keys in your Marketplace account. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html

  [Composer\Downloader\TransportException]
  The 'https://repo.magento.com/packages.json' URL required authentication.
  You must be using the interactive console to authenticate

**Comment by DIYlover** [comment]
Same here.  I got same basic authentication failure issue. 

I also tried to run composer command via shell directly, the result is positive.  It did prompted me for credential and I key-in exactly the same set of username + password (public + private keys) as written in "auth.json" file which stored at debian_config\composer\auth.json, it works!

**Environment info.**
Mac OS 10.14.5
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

**stdout for reference**
`$docker-compose up -d
Building m23
Step 1/12 : FROM mike/debian_config
 ---> 246eb434f210
Step 2/12 : MAINTAINER chandlerbing7@gmail.com
 ---> Using cache
 ---> cfd5c2080b07
Step 3/12 : RUN composer create-project --repository=https://repo.magento.com/ magento/project-community-edition /var/www/html/magento2ce/
 ---> Running in 630a6d8fc8b4
Creating a "magento/project-community-edition" project at "/var/www/html/magento2ce"
Warning from repo.magento.com: Your Magento authentication keys are invalid. Please double-check your keys in your Marketplace account. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
Warning from repo.magento.com: Your Magento authentication keys are invalid. Please double-check your keys in your Marketplace account. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
Warning from repo.magento.com: Your Magento authentication keys are invalid. Please double-check your keys in your Marketplace account. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html

                                                                             
  [Composer\Downloader\TransportException]                                   
  The 'https://repo.magento.com/packages.json' URL required authentication.  
  You must be using the interactive console to authenticate                  
                                                                             

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

ERROR: Service 'm23' failed to build: The command '/bin/sh -c composer create-project --repository=https://repo.magento.com/ magento/project-community-edition /var/www/html/magento2ce/' returned a non-zero code: 255`

**Comment by mike61988** [comment]
Hi,

I usually encountered such a problem when the "docker-compose up -d" or similar for windows command was run before valid keys were inserted in the auth.json file which means you got invalid keys inside the container. To be sure your keys are valid inside of the container just try to delete all images "docker images" - provides you within a list of all images, then "docker rmi -f <image_id>" for every single image, you may double-check the README.MD file for more details of how to do so.

Cheers

**Comment by mike61988** [comment]
The link below:
https://github.com/mike61988/magento2-dk#how-to-uninstall-the-vm

Cheers

**Comment by mike61988** [comment]
Hope that helps, let me know if it works
